name: Distro tar generator

on:
  push:

jobs:
  generate-distros:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Setup prerequisites
      run: |
        pacman -Syu --needed --noconfirm hub docker git
    - uses: actions/checkout@v3
    - name: Generate tars
      run: |
        docker rm $(docker ps --filter status=exited -q)
        bash wsl-tar-gen.sh
    - name: Generate release
      run: |
        set -x
        git status
        echo $PWD
        assets=()
        for asset in ./*.tar; do
          assets+=("-a" "$asset")
        done
        tag_name="WDT Release ${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$(date +%d%m%y)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}