name: Distro tar generator

on:
  push:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  generate-distros:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:latest

    steps:
    - name: Setup prerequisites
      run: |
        pacman -Syu --needed --noconfirm hub docker git
    - uses: actions/checkout@v3
    - name: Set date
      id: get-date
      run: |
        ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
        echo "date=$(/bin/date -u '+%d%m%Y%I%M')" >> $GITHUB_ENV
    - name: Generate tars
      run: |
        docker ps --filter status=exited -q | xargs docker rm || echo "Ignoring docker pruning"
        git config --global --add safe.directory /__w/wsl-distro-tars/wsl-distro-tars
        bash wsl-tar-gen.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ env.date }}
         release_name: WDT Release ${{ env.date }}
    - name: Upload WDT tars
      uses: xresloader/upload-to-github-release@v1.3.9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.tar"
        release_id: ${{ steps.create_release.outputs.id }}
