name: Distro tar generator

on:
  push:

jobs:
  generate-distros:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Setup prerequisites
      run: |
        pacman -Syu --needed --noconfirm hub docker git
    - uses: actions/checkout@v3
    - name: Set date
      id: get-date
      run: |
        ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
        echo ::set-output name=date::$(/bin/date -u "+%d%m%Y")
    - name: Generate tars
      run: |
        docker ps --filter status=exited -q | xargs docker rm || echo "Ignoring docker pruning"
        git config --global --add safe.directory /__w/wsl-distro-tars/wsl-distro-tars
        bash wsl-tar-gen.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ steps.get-date.outputs.date }}
         release_name: WDT Release ${{ github.ref }}
    - name: Upload alpine tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./alpine-${{ steps.get-date.outputs.date }}.tar
        asset_name: alpine-${{ steps.get-date.outputs.date }}.tar
        asset_content_type: application/tar
    - name: Upload archlinux tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./archlinux-${{ steps.get-date.outputs.date }}.tar
        asset_name: archlinux-${{ steps.get-date.outputs.date }}.tar
        asset_content_type: application/tar
    - name: Upload centos tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./centos-${{ steps.get-date.outputs.date }}.tar
        asset_name: centos-${{ steps.get-date.outputs.date }}.tar
        asset_content_type: application/tar
    - name: Upload debian tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./debian-${{ steps.get-date.outputs.date }}.tar
        asset_name: debian-${{ steps.get-date.outputs.date }}.tar
        asset_content_type: application/tar
    - name: Upload fedora tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./fedora-${{ steps.get-date.outputs.date }}.tar
        asset_name: fedora-${{ steps.get-date.outputs.date }}.tar
        asset_content_type: application/tar
    - name: Upload ubuntu tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ubuntu-${{ steps.get-date.outputs.date }}.tar
        asset_name: ubuntu-${{ steps.get-date.outputs.date }}.tar
        asset_content_type: application/tar                              