name: Distro tar generator

on:
  push:

jobs:
  generate-distros:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Setup prerequisites
      run: |
        pacman -Syu --needed --noconfirm hub docker git
    - uses: actions/checkout@v3
    - name: Set date
      id: get-date
      run: |
        ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
        echo ::set-output name=date::$(/bin/date -u "+%d%m%Y")
    - name: Generate tars
      run: |
        docker ps --filter status=exited -q | xargs docker rm || echo "Ignoring docker pruning"
        git config --global --add safe.directory /__w/wsl-distro-tars/wsl-distro-tars
        bash wsl-tar-gen.sh
    - name: Generate release
      run: |
        set -x
        git status
        echo $PWD
        assets=()
        for asset in ./*.tar; do
          assets+=("-a" "$asset")
        done
        tag_name="WDT Release ${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$(date +%d%m%y)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}